name: task_connect_app
description: "A new Flutter project."

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  supabase_flutter: ^2.5.5
  drift: ^2.22.0
  provider: ^6.1.2
  flutter_local_notifications: ^18.0.0
  get: ^4.6.6
  icons_plus: ^4.0.0
  font_awesome_flutter: ^10.7.0
  path: ^1.8.3
  crypto: ^3.0.6
  shared_preferences: ^2.1.1
  sqflite: ^2.3.0
  http: ^1.1.0 # <-- Added for HTTP requests
  flutter_secure_storage: ^8.0.0 # <-- Added for token storage
  intl: ^0.18.0
  image_picker: ^1.2.0
  flutter_map: ^6.0.0
  latlong2: ^0.9.1
  geolocator: ^11.0.0
  pusher_channels_flutter: ^2.1.3
  flutter_paypal_payment: ^1.0.1 # <-- Added for PayPal payments
  webview_flutter: ^4.4.2 # <-- Required for PayPal
  


dev_dependencies:
  drift_dev: ^2.22.0
  build_runner: ^2.4.10
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
